module.exports = {
  address: 'address',
  company: 'company',
  user: 'user',
  item_type: 'item_type',
  country: 'country',
  state: 'state',
  shape: 'shape',
  inventory_location: 'inventory_location',
  size: 'size',
  item: 'item',
  item_info: 'item_info',
  item_image: 'item_image',
  related_item: 'related_item',
};
