version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8070:8080