version: '3.1'
services:
  server:
    build: .
    volumes:
      - .:/server-app
    ports:
      - ${APP_PORT}:${APP_PORT}
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB},${POSTGRES_TEST_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8070:8080
volumes:
  db-data: